[package]
name = "report"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
http = { version = "1.1.0", default-features = false }
jsonwebtoken = { version = "8", default-features = false, features = [
  "use_pem",
] }
octocrab = { version = "0.31.2" }
openssl = { version = "0.10.68", default-features = false, features = [
  "vendored",
] }
prost = { version = "0.12.6", default-features = false }
tokio = { version = "1.42.0", default-features = false, features = [
  "macros",
  "rt",
] }
tonic = { version = "0.12.3", default-features = false, features = [
  "transport",
  "tls",
  "tls-roots",
] }
tonic-health = { version = "0.12.3", default-features = false, features = [
  "transport",
] }
tonic-web = { version = "0.12.3", default-features = false }
tower-http = { version = "0.6.1", default-features = false, features = [
  "cors",
  "trace",
] }
tracing = { version = "0.1.41", default-features = false, features = ["log"] }
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
  "tracing-log",
  "fmt",
] }
uuid = { version = "1.11.0", default-features = false, features = ["v4"] }

[dependencies.service-apis]
git = "https://github.com/sited-io/service-apis.git"
features = ["sited_io-report-v1"]
